spark.jars                     /opt/spark/jars/iceberg-spark-runtime-3.5_2.12-1.4.3.jar,/opt/spark/jars/iceberg-aws-bundle-1.4.3.jar,/opt/spark/jars/hadoop-aws-3.3.4.jar,/opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar
spark.driver.extraClassPath    /opt/spark/jars/iceberg-spark-runtime-3.5_2.12-1.4.3.jar:/opt/spark/jars/iceberg-aws-bundle-1.4.3.jar:/opt/spark/jars/hadoop-aws-3.3.4.jar:/opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar
spark.executor.extraClassPath  /opt/spark/jars/iceberg-spark-runtime-3.5_2.12-1.4.3.jar:/opt/spark/jars/iceberg-aws-bundle-1.4.3.jar:/opt/spark/jars/hadoop-aws-3.3.4.jar:/opt/spark/jars/aws-java-sdk-bundle-1.12.262.jar
spark.sql.extensions            org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.lakehouse     org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakehouse.type hadoop
spark.sql.catalog.lakehouse.warehouse s3a://silver/iceberg
spark.hadoop.fs.s3a.impl        org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.path.style.access true
